---
title: 'IGM rough code'
author: 'Josh Vo'
date: 'Feb 28, 2024'
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
editor_options: 
  markdown: 
    wrap: 72
---

## Setup

```{r setup, include=FALSE}


setwd("C:/Users/vo_j4/Desktop/401 data")

# Load the dataset
IGM_data <-read.csv("GDIM_2023_03.csv")
gini_data <- read.csv("gini 1991-2017 feb 22, 2024.csv")

# Load the packages
library(fuzzyjoin)
library(leaps)
library(dplyr)
library(ggplot2)
library(sqldf)
library(kohonen) ## package to run SOM

```

## 1. Cleaning data
# 1.1. Gini dataset
```{r}
head(gini_data)
# Rename the variables
colnames(gini_data)[colnames(gini_data) == "X1991..YR1991."] <- "1991"
colnames(gini_data)[colnames(gini_data) == "X1992..YR1992."] <- "1992"
colnames(gini_data)[colnames(gini_data) == "X1993..YR1993."] <- "1993"
colnames(gini_data)[colnames(gini_data) == "X1994..YR1994."] <- "1994"
colnames(gini_data)[colnames(gini_data) == "X1995..YR1995."] <- "1995"
colnames(gini_data)[colnames(gini_data) == "X1996..YR1996."] <- "1996"
colnames(gini_data)[colnames(gini_data) == "X1997..YR1997."] <- "1997"
colnames(gini_data)[colnames(gini_data) == "X1998..YR1998."] <- "1998"
colnames(gini_data)[colnames(gini_data) == "X1999..YR1999."] <- "1999"
colnames(gini_data)[colnames(gini_data) == "X2000..YR2000."] <- "2000"
colnames(gini_data)[colnames(gini_data) == "X2001..YR2001."] <- "2001"
colnames(gini_data)[colnames(gini_data) == "X2002..YR2002."] <- "2002"
colnames(gini_data)[colnames(gini_data) == "X2003..YR2003."] <- "2003"
colnames(gini_data)[colnames(gini_data) == "X2004..YR2004."] <- "2004"
colnames(gini_data)[colnames(gini_data) == "X2005..YR2005."] <- "2005"
colnames(gini_data)[colnames(gini_data) == "X2006..YR2006."] <- "2006"
colnames(gini_data)[colnames(gini_data) == "X2007..YR2007."] <- "2007"
colnames(gini_data)[colnames(gini_data) == "X2008..YR2008."] <- "2008"
colnames(gini_data)[colnames(gini_data) == "X2009..YR2009."] <- "2009"
colnames(gini_data)[colnames(gini_data) == "X2010..YR2010."] <- "2010"
colnames(gini_data)[colnames(gini_data) == "X2011..YR2011."] <- "2011"
colnames(gini_data)[colnames(gini_data) == "X2012..YR2012."] <- "2012"
colnames(gini_data)[colnames(gini_data) == "X2013..YR2013."] <- "2013"
colnames(gini_data)[colnames(gini_data) == "X2014..YR2014."] <- "2014"
colnames(gini_data)[colnames(gini_data) == "X2015..YR2015."] <- "2015"
colnames(gini_data)[colnames(gini_data) == "X2016..YR2016."] <- "2016"
colnames(gini_data)[colnames(gini_data) == "X2017..YR2017."] <- "2017"

head(gini_data$`1991`)

# empty NAs cells instead of ",,"
columns_to_process <- colnames(gini_data)[5:ncol(gini_data)] ## specify the columns to be processed (from "1991" to "2017")

for (col in columns_to_process) { ## loop through each specified column and replace ".." with ""
  gini_data[gini_data[[col]] == "..", col] <- ""
  gini_data[[col]] <- as.numeric(gini_data[[col]])
}
```

# 1.2. IGM dataset

```{r, warning=FALSE}
# add a new variable "gini" to IGM_data
IGM_data$gini <- NA

# match gini values to each datapoints using country code & year 
for (i in 1:nrow(IGM_data)) {
  # extract year, country, code columns
  country_code <- IGM_data$code[i]
  temp_year <- as.character(IGM_data$year[i])

  # find corresponding column in gini_data
  col_name <- temp_year  # Assuming column names are just the years
  
  # match the Country.Code and assign the value to "gini"
  IGM_data$gini[i] <- gini_data[gini_data$Country.Code == country_code, col_name]
}

# quick look at gini
summary(IGM_data$gini)

# examine why NAs exist
na_gini_data <- IGM_data %>% # filter all NAs to see what countries and years they are
  select(year, country, code, starts_with("gini")) %>%
  filter(across(starts_with("gini"), is.na)) %>%
  distinct() # delete duplicates


# NEED TO FIGURE OUT NEAREST VALUES FOR THESE  NAS
```

## 2. EDA

```{r}
# column indices of columns I want to examine
which(colnames(IGM_data) == "BHQ1_lb")
which(colnames(IGM_data) == "BHQ4_ub")

# subset columns we're interested in and examine IGM variables
BH_vars_data <- IGM_data[50:61]
summary(IGM_data[51:61])
# identify NAs
na_BHs <- IGM_data %>%
    filter(across(starts_with("BHQ1_lb"), is.na, .names = "keep"))
# delete all NAs from BH_vars_data
BH_vars_data <- BH_vars_data %>% na.omit() 

# checking correlation between all BH variables
cor(BH_vars_data)

ggplot(as.data.frame(as.table(cor(BH_vars_data))), aes(Var1, Var2, fill = Freq)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(title = "Correlation Heatmap", x = "", y = "")
```

## SOM 

```{r}
# normalize data
normalized_BH <- scale(BH_vars_data)
# choose grid dimensions (5x5)
som_grid <- somgrid(xdim = 5, ydim = 5, topo = "hexagonal")
# train SOM
som_model <- som(normalized_BH, grid = som_grid, rlen = 100, alpha = c(0.05, 0.01))
# visualize output
plot(som_model, type = "counts")
plot(som_model)
plot(umat(som_model), main = "U-matrix")

```
